### ISSUE TITLE
Error installing hmmlearn

### ISSUE THREAD

**Issue by zukowski** [Archethought/nn-learn#1]
When I run `pip install -r requirements.txt` the install fails to install hmmlearn with the following error:

```
InsecurePlatformWarning
Downloading hmmlearn-0.1.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-build-wfYdCx/hmmlearn/setup.py", line 13, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```

Has anyone seen this before or have any advice on what might be going on?

I'm running Python 2.7.6 in this venv.

**Comment by dixon1e** [comment]
https://github.com/hmmlearn/hmmlearn

This has to be install in the directory, missed it. Will update doco in about an hour.

**Comment by dixon1e** [comment]
hmmlearn is not the problem. working on the ordering of the requirements.txt

**Comment by zukowski** [comment]
Rearranging the order of dependencies in `requirements.txt` seems to have done the trick for me. I now have all the packages installed.

**Comment by dixon1e** [comment]
When using Mac OS X you have to have an X11 installed or the Plot window may not appear. Use XQuartz http://www.xquartz.org/

**Comment by zukowski** [comment]
Rearranged requirements.txt worked to get everything installed correctly. Closing.
